config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "events#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check


  resources :events, only: [:show, :new, :create, :edit, :update, :destroy] do
    resources :chatrooms, only: [:show, :new, :create] do
      resources :messages, only: [:create]
    end
    resources :bookings, only: [:create]
  end

  resources :bookings, only: [:destroy]
  resources :chatrooms, only: [:destroy]
  resources :messages, only: [:destroy]

  get "dashboard", to: "pages#dashboard"
  get "chat_dashboard", to: "pages#chat_dashboard"
  get "profile", to: "pages#profile"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :event_categories
  has_many :events, through: :event_categories

  def name_with_icon
    "#{icon} #{name}".html_safe
  end
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages, dependent: :destroy
  belongs_to :event
  has_many :user
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :bookings, dependent: :destroy
  belongs_to :user
  has_one :chatroom, dependent: :destroy
  has_one_attached :photo
  has_many :event_categories, dependent: :destroy
  has_many :categories, through: :event_categories
  # has_many :messages, through: :chatroom ??

  validates :title, presence: true
  validates :date, presence: true
  validates :time, presence: true
  validates :description, presence: true
  validates :venue_name, presence: true
  validates :venue_address, presence: true
  validates :price, presence: true
  validates :capacity, presence: true
  # validates :category_ids, presence: true
  include PgSearch::Model
  pg_search_scope :search_by_title_and_description,
    against: [ :title, :description ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }

  geocoded_by :venue_address
  after_validation :geocode, if: :will_save_change_to_venue_address?
end

# validate :validate_category_selection

# private

# def validate_category_selection
#   if category_ids.length < 1 || category_ids.length > 3
#     errors.add(:base, "Please select 1-3 categories.")
#   end
# end

app/models/event_category.rb
class EventCategory < ApplicationRecord
  belongs_to :event
  belongs_to :category
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chatroom

  validates :content, presence: true

  def sender?(a_user)
    user.id == a_user.id
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :messages, dependent: :destroy
  has_many :chatrooms, through: :messages
  has_one_attached :photo
  has_many :events
  has_many :bookings
  has_many :bookings_as_org, through: :events, source: :bookings

  validates :username, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  #:configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :photo])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def create
    @booking = Booking.new
    @event = Event.find(params[:event_id])
    @booking.event = @event
    @booking.user = current_user
    if @booking.event.attendees.to_i < @booking.event.capacity.to_i
      @event.update(attendees: @event.attendees + 1)
      @booking.save
      redirect_to @booking.event, notice: "Woohoo! You're going to #{@booking.event.title} on #{@booking.event.date}!" # change redirect to dashboard
    else
      redirect_to @booking.event, alert: "Sorry! This event is fully booked 🥲"
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to dashboard_path, status: :see_other
  end

  private

  def booking_params
    params.require(:booking).permit(:event_id)
  end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  def show
    @event = Event.find(params[:id])
    @chatroom = Chatroom.find(params[:id])
    @message = Message.new
    #redirect_to event_chatroom_path(@chatroom)
  end

  def create
  end

  def update
  end

  private

  def chatroom_params
    params.require(:chatroom).permit(:event_id)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def index
    @events = Event.all
    @events = Event.search_by_title_and_description(params[:query]) if params[:query].present?
    @events = @events.near(params[:location], 2) if params[:location].present?
    @events = @events.where(date: params[:date]) if params[:date].present?
    case params[:capacity]
    when "ALL"
      # Do nothing, get all events
    when "<30"
      @events = @events.where("capacity < ?", 30)
    when "30-60"
      @events = @events.where(capacity: 30..60)
    when "60+"
      @events = @events.where("capacity > ?", 60)
    end
    if params[:price].present? && params[:price] == "1"
      @events = @events.where(price: 0)
    end
    @events = @events.joins(:categories).where(categories: { id: params[:category_ids] }).distinct if params[:category_ids].present?
    map_markers(@events)
  end

  def show
    @booking = Booking.new
    @marker = [{ lat: @event.latitude, lng: @event.longitude,
    info_window_event_html: render_to_string(partial: "info_window_event", locals: {event: @event}) }]
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.user = current_user
    if @event.save
      @event.category_ids = params[:event][:category_ids]
      create_chatroom_event(@event)
      redirect_to event_path(@event)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @event.update(event_params)
    redirect_to event_path(@event)
  end

  def destroy
    if @event.user == current_user
      @event.destroy
      redirect_to root_path, status: :see_other
    else
      redirect_to _path(@event)
    end
  end

  private

  def map_markers(events)
    @markers = events.geocoded.map do |event|
    {
      lat: event.latitude,
      lng: event.longitude,
      info_window_index_html: render_to_string(partial: "info_window_index", locals: {event: event}),
    }
    end
  end

  def create_chatroom_event(event)
    Chatroom.create(event: event)
  end

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :date, :time, :category, :description, :venue_name,
                                  :venue_address, :capacity, :price, :photo, category_ids: [])
    # params.require(:event_category).permit(:category)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
  end

  def create
    @chatroom = Chatroom.find(params[:chatroom_id])
    @message = Message.new(message_params)
    @message.chatroom = @chatroom
    @message.user = current_user
    if @message.save!
      ChatroomChannel.broadcast_to(
        @chatroom,
        message: render_to_string(partial: "message", locals: {message: @message}),
        sender_id: @message.user.id
      )
      head :ok
    else
      render "chatrooms/show", status: :unprocessable_entity
    end
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # def home
  # end

  def dashboard
    @bookings_as_attendee = current_user.bookings
    @bookings_as_org = current_user.bookings_as_org
    @events_as_org = current_user.events
  end

  def chat_dashboard
    @bookings_as_attendee = current_user.bookings
    @bookings_as_org = current_user.bookings_as_org
    @events_as_org = current_user.events
  end

  def profile
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<h2>here are you bookings</h2>

app/views/chatrooms/show.html.erb
<div class="chatroom-back"
  data-controller="chatroom-subscription"
  data-chatroom-subscription-chatroom-id-value="<%= @chatroom.id %>"
  data-chatroom-subscription-current-user-id-value="<%= current_user.id %>"
>

<div class="">
  <div data-controller="headline" data-headline-chat-value="About joining <%= @chatroom.event.title %>...">
  <h2 class="htwo"></h2>
</div>
</div>

<div class="chatroom-container">
  <div class="messages" data-chatroom-subscription-target="messages">
    <% @chatroom.messages.each do |message| %>
    <div class= "<%= message.sender?(current_user) ? 'justify-content-end' : 'justify-content-start' %>">
      <div class="<%= message.sender?(current_user) ? 'sender-style' : 'receiver-style' %>">
        <%= render "messages/message", message: message %>
      </div>
    </div>
    <% end %>
  </div>

  <div class="chat-form">
    <%= simple_form_for [@event, @chatroom, @message],
      html: { data: { action: "turbo:submit-end->chatroom-subscription#resetForm" }, class: "chat-form"} do |f|
    %>
      <%= f.input :content,
        label: false,
        placeholder: "Message ##{@chatroom.event.title}",
        wrapper_html: {class: "chat-typing-box"},
        input_html: {class: "chat-input-box", }
      %>
      <%= f.submit "Send", class: "chat-btn" %>
    <% end %>
  </div>
</div>

</div>

app/views/events/_index_event_image.html.erb
<% if event.photo.attached? %>
  <%= cl_image_tag event.photo.key, class: "pic" %>
<% else %>
  <img src="<%= event.image_url%>" alt="event image">
<% end %>

app/views/events/_index_map.html.erb
<div
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

app/views/events/_info_window_event.html.erb
<h4><%= @event.venue_name %></h4>
<p><%= @event.venue_address %></p>

app/views/events/_info_window_index.html.erb
<% if event.photo.attached? %>
  <%= cl_image_tag event.photo.key, class: "mapbox-index-img"%>
<% else %>
  <img src="<%= event.image_url%>" alt="event image", class="mapbox-index-img">
<% end %>
<h6 class="info_title"><strong><%= link_to "#{event.title}", event_path(event)%></strong></h6>
<h6><%=event.venue_name %></h6>
<p><%= event.venue_address %></p>

app/views/events/_show_map.html.erb
<div>
  <div class="event-card"
  data-controller="map" data-map-target="map"
  data-map-markers-value="<%= @marker.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
</div>

app/views/events/_show_page_booker_btn.html.erb
<% if (@event.user != current_user) && (!(@event.bookings.select { |booking| booking.user == current_user }.empty?)) %>
  <div class="show_buttons_attending">
    <button class="btn-ghost-violet">Attending</button>
    <%= link_to "My bookings", dashboard_path(@event.id, @event.chatroom.id), class:"btn-violet btn-dashboard" %>
    <%= link_to "Let's talk!", event_chatroom_path(@event.id, @event.chatroom.id), data: {turbo: false}, class:"btn-violet btn-chat" %>
  </div>
<% elsif @event.user == current_user %>
  <div class="show-buttons-org">
    <%= link_to "Let's talk!", event_chatroom_path(@event.id, @event.chatroom.id), data: {turbo: false}, class:"btn-ghost-violet" %>
    <%= link_to "Edit event", edit_event_path(@event.id), class:"btn-violet btn-edit" %>
    <%= link_to "Delete event", event_path(@event.id), data: {turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this event?"}, class:"btn-violet btn-delete" %>
  </div>
<% elsif (@event.user != current_user) && (@event.attendees == @event.capacity) %>
  <div class="show_button_one">
    <button class="btn-ghost-neutral">Join the waiting list</button>
  </div>
<% elsif @event.user != current_user %>
<div class="show_button_one">
  <%= link_to "I'm going!", event_bookings_path(@event.id), class:"btn-violet", data: {turbo_method: :post} %>
</div>
<% end %>

app/views/events/_show_page_image.html.erb
<% if @event.photo.attached? %>
  <%= cl_image_tag @event.photo.key, class: "show_pic" %>
<% else %>
  <img src="<%= @event.image_url%>" alt="event image", class="show_pic">
<% end %>

app/views/events/edit.html.erb
<div class="edit-event-back">
  <div data-controller="headline" data-headline-edit-value="Wanna change something<br>...">
    <h1 class="header-index"></h1>
</div>

<div class="form-edit-event">

<h3>...about your event <%= @event.title %></h3>
<%= simple_form_for(@event) do |f| %>
  <%= f.input :title %>
  <%= f.input :date %>
  <%= f.input :time %>
  <%= f.input :description %>
  <%= f.label :category_ids, "Categories - please choose between 1-3:" %>
  <div data-controller="categoryselect">
    <%= f.collection_check_boxes :category_ids, Category.all, :id, :name_with_icon do |category| %>
    <div class = "tag-item">
      <%= category.check_box class:"tag-selector", data: {action: "click->categoryselect#activate", categoryselect_target: "input" }%>
      <%= category.label do %>
        <%= content_tag(:i, '', class: category.object.icon) %> <%= category.object.name %>
      <% end %>
    </div>
    <% end %>
  </div>
  <%= f.input :venue_name %>
  <%= f.input :venue_address, wrapper_html: { data: { controller: 'address-autocomplete', address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"] } },
              input_html: { data: { address_autocomplete_target: "location" },
              style: "display: none;" } %>
  <%= f.input :capacity %>
  <%= f.input :price %>
  <%= f.input :photo, as: :file %> <!-- should be image upload with Cloudinary -->
  <%= f.submit "Submit", class:"btn-new-event" %>
<% end %>
</div>

</div>

app/views/events/index.html.erb
<div class="event-background">
<div class="event-background-two">

  <div
  data-controller="headline" data-headline-name-value="<%= current_user.username %>">
    <h1 class="header-index"></h1>
  </div>

  <!-- Button to trigger Popup -->
  <button type="button" class="btn btn-ghost-orange-filter" data-bs-toggle="modal" data-bs-target="#exampleModal">
    Filter
  </button>

  <!-- Popup -->
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">

        <div class="modal-header">
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>

        <div class="modal-body" data-controller="search-form">
          <div class="search-form" data-search-form-target="form">
            <%= form_with url: root_path, method: :get do |form| %>
            <div class="reset">
              <%= button_tag 'Reset', class: "reset-btn", :type => 'reset' %>
            </div>
              <%= text_field_tag :query, params[:query],
                                class: "form-control",
                                placeholder: "I'm looking for..." %>
              <div data-controller="address-autocomplete" data-address-autocomplete-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>" class="search-text">
                <%= form.label :location, "Location:" %>
                <%= form.text_field :location, id: "location", placeholder: "Location", class: "d-none",
                                    data: {address_autocomplete_target: "location" }%>
              </div>
              <%= form.date_field :date, value: params[:date], placeholder: "Date", class: "form-control", placeholder: "Select a date" %>
              <div class="row">
                <div class="col-6 search-text">
                  <%= form.label :capacity, "Capacity" %>
                  <%= form.select :capacity, [["All events", "ALL"] ,["Keep it cozy", "<30"], ["I'm feeling social", "30-60"], ["The bigger the better!", "60+"]], selected: "ALL", class: "form-select"%>
                </div>
                <div class="col-3"></div>
                <div class="col-3 search-text">
                  <%= form.check_box :price %>
                  <%= form.label :price, "FREE" %>
                </div>
              </div>
              <fieldset>
                <% Category.all.each do |category| %>
                  <div class="tag-item">
                    <%= check_box_tag "category_ids[]", category.id, params[:category_ids]&.include?(category.id), id: "category_#{category.id}", class: "tag-selector form-control" %>
                    <%= label_tag "category_#{category.id}" do %>
                      <%= content_tag(:i, '', class: category.icon) %> <%= category.name %>
                    <% end %>
                  </div>
                <% end %>
              </fieldset>
              <%= form.submit "Search", class: "btn btn-ghost-orange-search", data: { action: "click->search-form#submit" } %>
              <!--<%= submit_tag "Search", class: "btn btn-ghost-orange-search" %>-->
            <% end %>

          </div>
        </div>

        <div class="modal-footer">
        </div>

      </div>
    </div>
  </div>


  <% if @events.empty? %>
    <div class="no-match">
      <h4>No events match your search, but fear not! We have plenty of other cool events for you to check out <u><%= link_to "HERE", root_path %></u></h4>
    </div>
  <% else %>
    <div class="toggle" data-controller="toggle map"
          data-map-markers-value="<%= @markers.to_json %>"
          data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      <div class="toggle-btn">
        <label class="switch">
          <input type="checkbox" id="togBtn" data-action="click->toggle#checked click->map#resize">
            <div class="slider round">
              <span class="list">List</span>
              <span class="map">Map</span>
            </div>
        </label>
      </div>

      <div class="events-list" data-toggle-target="list">
        <% @events.each do |event| %>
          <div class="event-card" style='background-image: url("<%= event.photo.attached? ? cl_image_tag(event.photo.key) : event.image_url%>")'>

      <div class="event-container">
            <div class="event-title">
              <h3 class="h3"><%= link_to event.title, event_path(event) %></h3>
            </div>

            <div class="event-infos">
              <p class="body-all"><%= event.date.strftime('%a. %e %b')%>  <%= event.time.strftime('%-l%P').downcase%></p>
              <p class="body-all-venue"><%= event.venue_name %></p>
            </div>
              </div>
          </div>
        <% end %>
      </div>

      <div class="d-none" data-toggle-target="mapbox" style="height: 400px">
        <div>
          <div class="mapstyle" data-map-target="map"></div>
        </div>
      </div>
    </div>
  <% end %>

</div>
</div>

app/views/events/new.html.erb
<div class="new-event-back">
  <div data-controller="headline" data-headline-new-value="I want to organize something<br>...">
      <h1 class="header-index"></h1>
  </div>


  <div class="form-new-event">

  <%= simple_form_for(@event) do |f| %>
    <%= f.input :title %>
    <%= f.input :date %>
    <%= f.input :time %>
    <%= f.input :description %>
    <%= f.label :category_ids, "Categories - please choose between 1-3:" %>
    <div data-controller="categoryselect">
      <%= f.collection_check_boxes :category_ids, Category.all, :id, :name_with_icon do |category| %>
      <div class = "tag-item">
        <%= category.check_box class:"tag-selector", data: {action: "click->categoryselect#activate", categoryselect_target: "input" }%>
        <%= category.label do %>
          <%= content_tag(:i, '', class: category.object.icon) %> <%= category.object.name %>
        <% end %>
      </div>
      <% end %>
    </div>
    <%= f.input :venue_name %>
    <%= f.input :venue_address, wrapper_html: { data: { controller: 'address-autocomplete', address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"] } },
                input_html: { data: { address_autocomplete_target: "location" },
                style: "display: none;" } %>
    <%= f.input :capacity %>
    <%= f.input :price %>
    <%= f.input :photo, as: :file %> <!-- should be image upload with Cloudinary -->
    <%= f.submit "Create event", class:"btn-new-event" %>
  <% end %>
  </div>

</div>

app/views/events/show.html.erb
<div class="show-background">
  <div class="image_container">
    <%= render "show_page_image" %>
    <div class="text_overlay">
      <h1><strong><%=@event.date.strftime('%a. %e %b')%>,</strong></h1>
      <h1><strong><%= @event.time.strftime('%-l%P').downcase %></strong></h1>
    </div>
  </div>
  <div class="show-buttons">
    <%= render "show_page_booker_btn" %>
  </div>
  <div class="infos">
    <div class="event_info">
      <p class="info_heading">EVENT</p>
      <div class="row">
        <div class="col-9">
          <h3><%= @event.title %></h3>
        </div>
        <div class="col-3" style="display: flex; flex-direction: column; justify-content: flex-end; align-items: flex-end;">
          <h3><i class="fa-regular fa-user"></i> <%= @event.capacity %></h3>
          <p><%= @event.price%> €</p>
        </div>
      </div>
      <p>What to expect: <%= @event.description %></p>
      <div>
        <% @event.categories.each do |category| %>
          <span class="category_show_display mt-2">
            <i class="<%=category.icon%>"></i> <%= category.name %>
          </span>
        <% end %>
      </div>
      <p class="attendees">So far, <strong><%= @event.attendees %></strong> people are attending this event.</p>
    </div>
    <div class="org_info">
      <p class="info_heading">ORGANISER</p>
      <h3><%= @event.user.username %></h3>
      <p><%= @event.user.bio %></p>
    </div>
    <div class="venue_info">
      <p class="info_heading">VENUE</p>
      <h3><%= @event.venue_name %></h3>
      <p><%= @event.venue_address %></p>
      <!--<p>Accessibilty: </p>-->
    </div>
  </div>

  <div class="show-map">
    <%= render "show_map" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CultureWeb</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <meta name="apple-mobile-web-app-capable" content="yes">
      <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <script src="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v4.7.0/mapbox-gl-geocoder.min.js"></script>
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.5.1/mapbox-gl.js"></script>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <link rel="stylesheet" href="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v5.0.0/mapbox-gl-geocoder.css" type="text/css">
    <link rel="manifest" href="<%= asset_path 'manifest.json' %>">
    <%= render 'shared/ios_pwa_links' %>
<%# neu  %>
    <meta name="viewport" content="width=device-width, initial-scale=1"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css">
    <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Playfair+Display:700|Raleway:500.700'>
<%# neu  %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="mobile-web-app-capable" content="yes">

  </head>

  <body>
    <%= render "shared/flashes" %>
    <main><%= yield %></main>
    <nav><%= render "shared/navbar" %></nav>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="message-card" id="message-<%= message.id %>">
  <small>
    <%= cl_image_tag message.user.photo.key, class: "avatar" %> <strong><%= message.user.username %></strong>
    <i><%= message.created_at.strftime("%a %b %e at %l:%M %p") %></i>
  </small>
  <p><%= message.content %></p>
</div>

app/views/pages/_bookings_as_attendee.html.erb
<div class= "my-bookings">
  <h1>...attending:</h1>
  <% @bookings_as_attendee.each do |booking| %>
    <hr>
    <div class="flex-container">
      <div class="flex-box-one">
        <p><%= booking.event.venue_name %></p>
        <h3><%= link_to booking.event.title, event_path(booking.event) %></h3>
        <div class= "date-time">
          <p><strong><%=booking.event.date%></p>
          <%= link_to "Cancel", booking_path(booking.id), data: {turbo_method: :delete, turbo_confirm: "Are you sure you want to cancel this booking?"}, class:"btn btn-ghost-orange-chancel" %>
        </div>
      </div>
      <hr>
    </div>
  <% end %>
</div>

app/views/pages/_events_as_org.html.erb
<div class= "my-bookings">
  <h1>...organizing:</h1>
  <% @events_as_org.each do |event| %>
  <hr>
    <div class="flex-container">
      <div class="flex-box-one">
        <p><%= event.venue_name %></p>
        <h3><%=link_to event.title, event_path(event)%></h3>
        <div class= "date-time">
          <p><strong><%=event.date%></p>
        </div>
      </div>
      <hr>
      <div class="attendees">
        <div class="flex-box-one"><i class="fa-regular fa-user"></i><h3><%= event.attendees %></h3></div>
      </div>
    </div>
  <% end %>
</div>

app/views/pages/dashboard.html.erb
<div class="dashboard-background">

<div data-controller="headline" data-headline-bookings-value="Here are the events you're...">
    <h1 class="header-all"></h1>
</div>

<div class="booking-list" data-controller="toggle">

  <div class="chat-toggle">
    <label class="switch">
    <input type="checkbox" id="togBtn" data-action="click->toggle#toggleBookingList">
    <div class="slider round">
      <span class="attending"></span>
      <span class="organising"></span>
    </div>
    </label>
  </div>

  <div class="container-booking" data-toggle-target="attBookings">
    <% if current_user.bookings.exists? %>
      <%= render "bookings_as_attendee" %>
    <% else %>
      <%= render "no_events" %>
    <% end %>
  </div>



      <!--<div class= "not">
        <body-all > Give a fuck (no attendance) </body-all>
      </div>-->
  <!--<hr>
  <div class="my-events">

    <div class= "headline-my-events">
    <div data-controller="headline" data-headline-events-value="My<br>events">
        <h1 class="header-all"></h1>
    </div>
    </div>-->



    <div class="container-event d-none" data-toggle-target="orgBookings">
      <% if current_user.events.exists? %>
        <%= render "events_as_org" %>
      <% else %>
        <div class= "not-two">
            <body-all > You lazy fuck (no events) </body-all>
            </div>
        <%= link_to "New event, new life ", new_event_path, class:"btn btn-ghost-orange-new_event" %>
      <% end %>
    </div>
  </div>
  <hr>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/profile.html.erb
<h1>Hello</h1>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="icon-button">
    <%= link_to "", destroy_user_session_path, data: {turbo_method: :delete}, class:"fa-solid fa-circle-user" %>
    <%= link_to "", chat_dashboard_path, class:"fa-regular fa-comment" %>

    <%= button_to(root_path, method: :get, class: "image-button") do %>
  <%= image_tag("https://res.cloudinary.com/dsj3cc5zj/image/upload/v1701686124/CWlogo_bnd2h7.png", alt: "Home Button") %>
<% end %>

    <%= link_to "", new_event_path, class:"fa-regular fa-calendar-plus" %>
    <%= link_to "", dashboard_path, class:"fa-regular fa-calendar-days" %>

  </div>
</div>